version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: doublelayer/ffmpeg-converter-service
    container_name: ffmpeg-converter-service
    deploy:
      mode: replicated
      replicas: 6
      labels: [APP=APP]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
    ports:
      - '9025:3000'
