version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: doublelayer/ffmpeg-converter-service
    container_name: ffmpeg-converter-service
    ports:
      - '9025:3000'
